all:
  children:
    test:
      hosts:
        server1_test:
        server2_test:
        server3_test:

    production:
      hosts:
        server1_prod: 
        server2_prod:
        server3_prod: