all:
  children:
    test:
      hosts:
        server1_test:
          ansible_host: host.docker.internal
          ansible_port: 2221
        server2_test:
          ansible_host: host.docker.internal
          ansible_port: 2222
        server3_test:
          ansible_host: host.docker.internal
          ansible_port: 2223

    production:
      hosts:
        server1_prod:
          ansible_host: 10.0.0.4  
        server2_prod:
          ansible_host: 10.0.0.155   
        server3_prod:
          ansible_host: 10.0.0.139  